name: Trigger Netlify Build
on:
  schedule:
    # Run at 2am
    - cron: '0 2 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/61a946452b5ca31cfec7f5fb
